os: linux
language: python
python:
  - "2.7"
  - "3.7"

# Cache the dependencies installed by pip
cache: pip
# Avoid pip log from affecting cache
before_cache: rm -fv ~/.cache/pip/log/debug.log

install:
  # Base requirements for ssm
  - pip install -r requirements.txt
  # Additional requirements for the unit and coverage tests
  - pip install -r requirements-test.txt

# Commands to prepare environment for the test
before_script:
  - export TMPDIR=$PWD/tmp
  - mkdir $TMPDIR
  - export PYTHONPATH=$PYTHONPATH:`pwd -P`
  - cd test

script: coverage run --branch --source=ssm,bin -m unittest discover --buffer

after_success:
  - coveralls
  - codecov
